### ISSUE TITLE
Redis response issues with Windows environments.

### ISSUE THREAD

**Issue by genariokas** [graknlabs/redis-mock#12]
Hi,

There is an issue where redis responses contains incorrect line endings for Windows environments.

Main issue is here: Response.java  and in multiple places it uses String.format to generate responses. For example the pattern in use String.format(":%d\r%n", v) %n will map to \r\n and final result here will be \r\r\n. Most redis clients will fail on this. A simple change to String.format(":%d\r\n", v) should be enough here.

Thanks

**Comment by fppt** [comment]
Hi @genariokas,

Thanks for reporting this issue. I am a bit busy at the moment and do not have access to a windows environment. I will try to get to it when I can.

In the meantime if you feel up for it maybe you could do a PR to resolve this issue since you are already familiar with it?

Thanks,

**Comment by genariokas** [comment]
Hi @fppt,
I've created a PR for this issue, please review it and if possible, release new version :)

Thanks.

**Comment by fppt** [comment]
Hi @genariokas,

Thanks so much for the fix. I have made a release with your fix. Can you confirm that it works and maybe close this issue if it does?

Thanks.

**Comment by genariokas** [comment]
Confirming, now my use cases are working properly.
